import type { NextPage } from "next";
import Head from "next/head";
import Button from "../components/Button";
import classes from "../styles/Grid.module.css";
import img1 from "../public/Images/thumb_article11.jpg";
import img2 from "../public/Images/thumb_article15.jpg";
import img3 from "../public/Images/thumb_article29.jpg";
import img4 from "../public/Images/thumb_article34.jpg";
import img5 from "../public/Images/thumb_article35.jpg";
import img6 from "../public/Images/thumb_article36.jpg";
import img7 from "../public/Images/thumb_article37.jpg";
import Card from "../components/Card";
import CategoriesNav from "../components/CategoriesNav";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Next Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CategoriesNav />
      <div className={classes.grid}>
        <Card image={img1} postSlug="you" />
        <Card image={img2} postSlug="you" />
        <Card image={img3} postSlug="you" />
        <Card image={img4} postSlug="you" />
        <Card image={img5} postSlug="you" />
        <Card image={img6} postSlug="you" />
        <Card image={img7} postSlug="you" />
      </div>
      <div className="flex gap-2 justify-center mt-3">
        <Button noMoreInPrevious>Previous</Button>
        <Button fill>Next</Button>
      </div>
    </>
  );
};

export default Home;
